name: Java CI with Gradle

on:
  push:
    branches: "**"
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Avocado
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: Copy secret env
        env:
          SECRET_ENV_DIR: src/main/resources
          SECRET_ENV_FILENAME: env.properties
        run: echo ${{ secrets.ENV_PROPERTIES }} > $SECRET_ENV_DIR/$SECRET_ENV_FILENAME
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ${{ env.working-directory }}

      - name: Test with Gradle
        run: ./gradlew --info test
        working-directory: ${{ env.working-directory }}
